//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JARVIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadDoc
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Allfiles { get; set; }
        public string Marksheet { get; set; }
        public string Aadhar_card { get; set; }
        public string PAN_card { get; set; }
        public string Passport { get; set; }
        public string Bank_stmt { get; set; }
        public string Revealing_letter { get; set; }
        public string Offer_letter { get; set; }
        public string Exp_certificate { get; set; }
        public string Latest_payslip { get; set; }
        public string Photo { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
